version: '3.3'

services:
  teach_me_celery_worker:
    build: ./
    command: celery -app=celery_app.worker_app worker --loglevel=INFO
    volumes:
      - ./:/teach_me_celery
    env_file:
      - ./.env_prod